# Generated by Django 4.0.2 on 2022-02-23 06:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dest',
            name='text',
            field=models.TextField(default=datetime.datetime(2022, 2, 23, 6, 32, 24, 586737, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
