# Generated by Django 4.0.2 on 2022-02-24 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_items_delete_dest'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='item_image',
            field=models.CharField(default='shorturl.at/gzR34', max_length=500),
        ),
    ]
